// Get all users
GET http://localhost:5000/api/users/

###

GET https://i6qsyfcfml.execute-api.ap-south-1.amazonaws.com/prod/api/users/all/account-managers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY


###

// Get user by username
GET http://localhost:5000/api/users/AksHay@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// user registration
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "docId": "1000",
    "username": "akshay",
    "email": "akshay@gmail.com",
    "phone": "6305332474",
    "password": "akshay123",
    "role": "ADMIN",
    "hiringFor": "Admin",
    "assignHM": "",
    "location": "Hanamkonda, Telangana",
    "hiringCategory": ["IT"],
    "resumeUrl": "",
    "hmType": ""
}

###

// user login
POST http://localhost:5000/api/users/login
Content-Type: application/json
    
{
    "email": "sai@gmail.com",
    "password": "sai123"
}

###

// Get all Account Managers
GET http://localhost:5000/api/users/all/account-managers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Get all HRs
GET http://localhost:5000/api/users/all/hr/account@victaman.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Post new Job
POST http://localhost:5000/jobs/add/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

{
    "companyName": "Google",
    "title": "Software Engineer",
    "category": "IT",
    "description": "Software Engineer",
    "location": "Bangalore",
    "minSalary": 10,
    "maxSalary": 20,
    "skills": "Java, Python, C++",
    "employmentType": "Full Time",
    "workType": "Work From Home",
    "commissionFee": 10,
    "commissionType": "Percentage",
    "noOfOpenings": 10,
    "status": "Open",
    "hiringNeed": "Urgent",
    "postedBy": "likki@gmail.com",
    "assignedTo": ["nahed@gmail.com", "akkiakshay440@gmail.com"],
    "shiftTimings": "morning"
}

###

// Get jobs Details
GET http://localhost:5000/jobs/details/5523d08b-8da5-48c9-b341-c3a50f3c44d8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// assign job to HR
POST http://localhost:5000/jobs/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY
    
{
    "jobId": "5523d08b-8da5-48c9-b341-c3a50f3c44d8",
    "assignedTo": "yash@gmail.com",
    "assignedBy": "nahed@gmail.com"
}

###

// Get all jobs for Account Manager
GET http://localhost:5000/jobs/account-manager/nahed@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Get all jobs for HR
GET http://localhost:5000/jobs/hr/yash@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Post candidate details
POST http://localhost:5000/jobs/candidate/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

{
    "fullName": "akshay",
    "fatherName": "raj kumar",
    "email": "akshay@gmail.com",
    "phone": "7410852096",
    "dateOfBirth": "04-02-2001",
    "gender": "Male",
    "aadharNumber": "12",
    "highestQualification": "Graduation",
    "currentLocation": "Bangalore",
    "spokenLanguages": ["English", "Telugu", "Hindi"],
    "experienceInYears": 2,
    "experienceInMonths": 5,
    "skills": ["Java", "Python", "C++", "C"],
    "jobCategory": "IT",
    "offerStatus": "Pending",
    "jobId": "2e13f0bd-ea6e-41d8-867f-600496742c58",
    "hrEmail": "yash@gmail.com",
}

###

// Get all candidates for Job
GET http://localhost:5000/jobs/candidate/2e13f0bd-ea6e-41d8-867f-600496742c58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Update candidate Job status
PUT http://localhost:5000/jobs/candidate/status/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

{
    "candidateId": "307581df-2a67-42d2-92e9-cc6774e1e9e6",
    "jobId": "5523d08b-8da5-48c9-b341-c3a50f3c44d8",
    "email": "yash@gmail.com",
    "offerStatus": "Selected"
}

###

// Get all candidates for HR
GET http://localhost:5000/jobs/candidates/yash@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Get candidate details
GET http://localhost:5000/jobs/candidate/details/e73204a9-6b95-49e1-a1b3-fe9c1e9bc780
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Get all users for Admin
GET http://localhost:5000/admin/get-users/all?role=null&isBlocked=null
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Get all candidates for Admin
GET http://localhost:5000/admin/get-candidates/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Get all jobs for Admin
GET http://localhost:5000/admin/get-jobs/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Update a Job to Archive
PUT http://localhost:5000/admin/archive-job/5523d08b-8da5-48c9-b341-c3a50f3c44d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Block a user
PUT http://localhost:5000/admin/block-user/prashob@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

// Unblock a user
PUT http://localhost:5000/admin/unblock-user/prashob@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY

###

GET http://localhost:5000/jobs/assigned-hr/82c52b87-39cc-4fb8-8e2f-d9eaaf015dc5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrc2hheSIsImlhdCI6MTcwMjY0NDY4N30.DZF3pL_MiHb5FWl_7ZqkjBZ2kEhiDbJcVlXmGzVUkJY