# service: gcloud-service

# provider:
#   name: google
#   stage: prod
#   runtime: nodejs16
#   region: asia-south1
#   project: earlyjobs
#   # credentials: ~/.gcloud/keyfile.json

# frameworkVersion: '3'

# plugins:
#   - serverless-google-cloudfunctions

# package:
#   exclude:
#     - node_modules/**
#     - .gitignore
#     - .git/**

# functions:
#   server:
#     handler: server
#     events:
#       - http: path


service: earlyjobs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  region: ap-south-1
  environment:

functions:
  app:
    handler: app.server
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5000
  apigwBinary:
    types:
      - "application/json"
      - "application/javascript"